# This is a basic workflow to validate JSON file using https://github.com/leadpony/justify

name: Justify JSON Schema

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download a file
        uses: carlosperate/download-file-action@v1.0.3
        id: download-poetry
        with:
          file-url: "https://github.com/leadpony/justify/releases/download/v3.0.0-RC1/justify-cli-3.0.0-RC1.zip"
          file-name: "justify-cli-3.0.0-RC1.zip"
          location: "./"

      - name: Unzip Justify
        run: unzip justify-cli-3.0.0-RC1.zip

      - name: Validate API JSON data
        run: justify-cli/justify -s schema.json -i database/*.json
